second_pro/sec_pro/urls.py
from django.conf.urls import url
from sec_pro import views

app_name = 'sec_pro'


urlpatterns = [
    # url(r'^$',views.index,name='index'),
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative')
]
 

second_pro/second_pro/urls.py
from django.contrib import admin
from django.urls import path
from sec_pro import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^sec_pro/',include('sec_pro.urls')),
    path('admin/', admin.site.urls),
]

second_pro/sec_pro/models.py
# Create your models here.

second_pro/sec_pro/views.py
from django.shortcuts import render

def index(req):
    Con ={'text': 'this is it', 'number':100}
    return render(req,'sec_pro/index.html',Con)

def other(req):
    return render(req,'sec_pro/other.html')

def relative(req):
    return render(req,'sec_pro/relative.html')

    


# Create your views here.

second_pro/templates/sec_pro/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Basr file</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navbar-brand">Brand</a></li>
                <li><a href="{% url 'admin:index' %}" class="navbar-link">Admin</a></li>
                <li><a href="{% url 'sec_pro:other' %}" class="navbar-link">Other</a></li>

                
                

            </ul>

        </div>
    </nav>
    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>



    
</body>
</html>

second_pro/templates/sec_pro/index.html
<!DOCTYPE html>
{% extends "sec_pro/base.html" %}
{% block body_block %}
<h1>this is index.html</h1>

<h1>{{text | cut:'is'}}</h1>
<h1>{{number | add:'99'}}</h1>
{% endblock %}

second_pro/templates/sec_pro/other.html
<!DOCTYPE html>
{% extends "sec_pro/base.html" %}
{% block body_block %}
<h1>this is others</h1>
{% endblock %}

second_pro/templates/sec_pro/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>the other</title>
</head>
<body>
    <a href="{% url 'sec_pro:other' %}">link to other</a>
</body>
</html>

templates/usero/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
    <nav class='navbar  navbar-default navbar-static-top'>
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'index' %}" class="navabr-brand">Django</a></li>
                <li><a href="{% url 'admin:index'%}" class="navabr-link">Admin</a></li>
                <li><a href="{% url 'usero:register' %}" class="navabr-link">Register</a></li>

                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="navbar-link">L ogout</a></li>
                {% else %}
                <li><a href="{% url 'usero:user_login' %}" class="navbar-link">Login</a></li>
                {% endif %}
            </ul>

        </div>

    </nav>
    {% block body_block %}

    {% endblock %}
    
</body>
</html>

templates/usero/index.html
<!DOCTYPE html>
{% extends 'usero/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django level five </h1>
</div>

{% endblock %}

templates/usero/login.html
{% extends 'usero/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>please login</h1>

    <form action="{% url 'usero:user_login' %}" method="post">
    {% csrf_token %}

    <label for="username">USername: </label>
    <input type="text" name="username" placeholder="username">

    <label for="password">password</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
</form>
</div>
{% endblock %}

templates/usero/register.html
{% extends 'usero/base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>thank you for registering!</h1>
    {% else %}
    <h1>register here </h1>
    <h2>fill out the form</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{profile_form.as_p}}

        <input type="submit" value="register">

    </form>
    {% endif %}

</div>
{% endblock %}